apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ include "kafka-pubsub-emulator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-pubsub-emulator.name" . }}
    helm.sh/chart: {{ include "kafka-pubsub-emulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-pubsub-emulator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kafka-pubsub-emulator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: config-init
          image: busybox
          command:
            - sh
            - '-c'
            - |
              echo '{{ .Values.server | toJson }}' > /etc/config/config.json
              echo '{{ .Values.pubsub | toJson }}' > /etc/config/pubsub.json
          volumeMounts:
            - name: persistent-config-volume
              mountPath: /etc/config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-c","/etc/config/config.json", "-p", "/etc/config/pubsub.json"]
          volumeMounts:
            - name: persistent-config-volume
              mountPath: /etc/config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
{{ toYaml . | indent 12 }}
          {{- end}}
          {{- with .Values.readinessProbe }}
          readinessProbe:
{{ toYaml . | indent 12 }}
          {{- end}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: persistent-config-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
